# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repgar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='fecha2',
        ),
    ]
